from typing import Any

class BME280:
    def __init__(self, ic2_dev: Any) -> None: ...
    def get_temperature(self) -> float: ...
    def get_pressure(self) -> float: ...
    def get_humidity(self) -> float: ...
